% **********************************************
%     Neville's Method Polynomial Interpolation
% **********************************************
% *
% *    Written by: Craig Medlin
% * Last Modified: March 10, 2016

function [ N ] = NevPoly(X, Y, xi)
%LagPoly This function interpolates a value for an unknown point
% given a set of x points and corresponding f(x) values using 
% the Lagrangian polynomial method.
%
%   INPUTS (required)
%         X - A set of n x values
%         Y - A set of n corresponding y values
%        xi - X value to interpolate for
% 
%   OUTPUTS 
%        N - Interpolated value at xi
%   nTable - Table generated by Neville's Method
%
%   EXAMPLE
%       X = [1.1 2.2 3.3 4.4];
%       Y = [6 12 3 6];
%       N = NevPoly(X,Y,3.1);
%

% Input validation
narginchk(3,inf);

% Initialization
N = 0; % Interpolated value
n = length(X);


